version: "3"

services:
  app:
    build:
      context: node
    container_name: app
    tty: true 
    entrypoint: wait-for db:3306 -t 40 -- ./start.sh
    volumes:
      - ./node:/home/node/app
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:8.2.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - ./mysql:/var/lib/mysql 
    networks: 
      - node-network
  
  nginx: 
    build:
      context: nginx
    container_name: nginx
    restart: always
    tty: true 
    networks: 
      - node-network
    ports:
      - "8080:80"

networks:
  node-network:
    driver: bridge